# Generated by Django 5.1.6 on 2025-02-23 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Books", "Books"),
                            ("Clothing", "Clothing"),
                            ("Furniture", "Furniture"),
                            ("Appliances", "Appliances"),
                            ("Automobiles", "Automobiles"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Like New", "Like New"),
                            ("Used", "Used"),
                            ("Fair", "Fair"),
                        ],
                        max_length=50,
                    ),
                ),
                ("seller", models.CharField(max_length=255)),
                ("seller_contact", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=255)),
                ("available", models.BooleanField(default=True)),
                ("listing_date", models.DateTimeField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "tags",
                    models.TextField(
                        blank=True,
                        help_text="Enter hashtags separated by spaces, e.g. #cat, #playstation",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listing_images/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "listings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
