# Generated by Django 5.1.7 on 2025-03-17 21:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_latitude_listing_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
